version: '3.7'

networks:
  nginx-php74-mysql8-node:

services:

  node:
    container_name: app
    build: .
    volumes:
      - './:/var/www/app/'
      - '.yarn:/var/www/app/.yarn'
      - './src:/var/www/app/src'
      - './package.json:/var/www/app/package.json'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: yarn start
